### PR TITLE
Food group fixes

### LINKED ISSUE #156: [ISSUE] - Nutrition groups and missing food recipes
I don't know if SoL supports custom nutrition (from a quick glance at the CF page anyway), but here's a list of items that I'll keep updated that don't have nutrition groups and what I think it should be

Notes:
- A lot of these don't have nutrition auto assigned because they don't have recipes assigned (or in some cases, can't be accessed by JEI)
- Some foods are also obtained only by placing a parent food and using a bowl/knife on it (see: guardian soup, plate of dragon leg, stuffed hoglin)
- A lot of other foods should be autofixed if they have foods that don't have nutrition groups in their recipes (see: ground strider, nether skewer)  
- I will also be excluding items that can be eaten, but don't give you hunger/saturation (see: healing stone)
 - Also, might want to consider adding a nutrition group for dairy? Seems to be a whole lot of it in foods

<hr>

GT:
- Purple drink (psi)

Ars:
- Mendosteen, Bastion fruit, Frostaya, Bombegranate (fruit, mana?)

Ad Astra
- Cheese (protein)

Botania:
- Biscuit of totality (grains, sugars; probably 5x of a cookie; probably a little bit of mana too)
- Mana in a bottle (mana, but definitely some absurdly low amount)

Croptopia:
- Chile Pepper (apparently pepper are fruits and not vegetables, but I'll leave this up to you)
- Coffee (vegetable and sugar???? idk man the recipe for this one is brokey, but coffee seeds count as vegetable)
- Pumpkin spice latte (also broken recipe, sugar and vegetable)
- Sea lettuce (vegetable)
- Frog legs (raw and fried) (protein)

Delightful:
- Matcha (vegetable? idk what tea leaves count as)
- Chopped clover, Lavender tea (same as above)
- Marshmallow stick (raw and roasted) (sugar)
- Bowl of stuffed cantaloupe (broken recipe) (grain, fruit, vegetable?)

Farmer's Delight:
- Apple cider (sugar, fruit)

Nether's Delight:
- Hoglin loin (protein; double of raw porkchop)
- Hoglin sirloin (protein; double of cooked porkchop)
- Hoglin ear (protein)
- Strider slice (protein)
- Plate of stuffed hoglin snout, ham, roast (vegetable, protein)
- Propelpearl (fruit imo)
- Magma gelatin (??? the fuck does magma cream count as?, fruit; fruit should count automatically once propelpearl has a nutrition group)

Occultism:
- Demon's dream seeds, demon's fruit (fruit? negative mana?)
- Demon's dream and overworld essence

Supplementaries:
- Soap :trollface: (protein technically)

The Aether:
- Blue berry, enchanted berry, white apple (fruit)
- Blue and golden gummy swets (sugar)
- Gingerbread man (sugar, grain)
- Candy cane (sugar)
- Rotten blisterberry (fruit, technically)

Vintage Delight:
- PB & J (missing recipe in JEI) (sugar, fruit, grain)

Cold Sweat:
- Cold sprout (fruit/vegetable?)

### PR DESCRIPTION
**Pull request by JuiceyBeans**
`I cannot be bothered to learn how to rebase PRs on deleted branches. Lmao`

Oh wowie. This one is gonna be hellish.

This PR will:
- Add missing diet groups to all foods
- ~~Add fertile season requirements to crops~~ Reducing PR scope so I don't burn out, maybe in the future
- Removes a brokey noodle extruding recipe
- Fix vegetable soup culinary assembler recipe
- Moves nutrition group definitions to Kube tag events instead of manually defined tags
- Adds builders for food in `ItemModification.js`
- Unifies a bunch of food-related tags

Closes #156

### CODE REVIEW

**Comment by JuiceyBeans** [comment]
For future reference, crops missing seasons are:
- Tea
- Yam
- Vanilla
- All the Undergarden and LSO crops, if you want to add seasons to them

File: overrides/kubejs/server_scripts/Recipes/Foods/Tags.js [hunk 1]
```diff
@@ -1,22 +1,186 @@
...
-    event.add('forge:salt', 'gtceu:salt_dust')
-    event.add('forge:rice', 'farmersdelight:rice')
-    event.add('forge:cabbage', 'farmersdelight:cabbage')
-    event.add('forge:tomatoes', 'farmersdelight:tomato')
-    event.add('forge:onions', 'farmersdelight:onion')
-    event.add('frontiers:croptopia/nuts', ['croptopia:almond', 'croptopia:pecan', 'croptopia:walnut']) // non peanut nuts from croptopia used for roasted nuts recipe
-    event.add('forge:peanuts', ['vintagedelight:peanut', 'croptopia:peanut']) // this is driving me *nuts* why does one have (s)
+// priority: 999
+
+ServerEvents.tags('item', e => {
```
Comment (Ghostipedia) [inline overrides/kubejs/server_scripts/Recipes/Foods/Tags.js]: Please make sure to always use 'event' instead of 'e'

File: overrides/kubejs/server_scripts/Recipes/Foods/Tags.js [hunk 2]
```diff
@@ -1,22 +1,186 @@
...
+
+    e.add('frontiers:croptopia/nuts', ['croptopia:almond', 'croptopia:pecan', 'croptopia:walnut']) // non peanut nuts from croptopia used for roasted nuts recipe
+    e.add('forge:peanuts', ['vintagedelight:peanut', 'croptopia:peanut']) // this is driving me *nuts* why does one have (s)
 })
 
-ServerEvents.tags('fluid', event => {
-    event.add('forge:milk', 'gtceu:soy_milk')
-    event.add('forge:milk', 'gtceu:milk')
-    event.add('forge:milk', 'minecraft:milk')
+ServerEvents.tags('block', e => {
```
Comment (Ghostipedia) [inline overrides/kubejs/server_scripts/Recipes/Foods/Tags.js]: Here as well

File: overrides/kubejs/server_scripts/Recipes/Foods/Tags.js [hunk 3]
```diff
@@ -1,22 +1,186 @@
...
+    // }
 })
 
-ServerEvents.tags('fluids', event => {
-    event.add('forge:milk', 'croptopia:soy_milk')
-    event.add('forge:milk', 'gtceu:milk')
-    event.add('forge:milk', 'minecraft:milk')
-})
\ No newline at end of file
+ServerEvents.tags('fluid', e => {
```
Comment (Ghostipedia) [inline overrides/kubejs/server_scripts/Recipes/Foods/Tags.js]: And here

File: overrides/kubejs/startup_scripts/ItemModification.js [hunk 4]
```diff
@@ -66,41 +97,5 @@ ItemEvents.modification(event => {
         item.addAttribute("malum:soul_ward_capacity", 'b504bc09-b827-4b24-867f-553dc6dc5345', 'ward-capacity7', 7.5, "addition")
         item.addAttribute("malum:soul_ward_recovery_rate", '9b8b37d0-913e-425e-bd65-b87056f85ec3', 'recovery-rate7', 2.0, "addition")
       })
-      //Quarktechs
```
Comment (Ghostipedia) [inline overrides/kubejs/startup_scripts/ItemModification.js]: Why did this get removed please make sure that this pr doesn't override the item modification for quark/nano armor!

**Review by Ghostipedia — CHANGES_REQUESTED** [review]

File: overrides/kubejs/startup_scripts/ItemModification.js (hunk 4 above)
Comment (JuiceyBeans) [reply overrides/kubejs/startup_scripts/ItemModification.js]: Was NOT supposed to be deleted, fixing now, dunno why it was in the first place

**Comment by Ghostipedia** [comment]
Im Mergemastering it
